packages:
  - "."
minimumReleaseAge: 0
ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
